### ISSUE TITLE
highway = motorway as way tag 

### ISSUE THREAD

**Issue by carles3** [perliedman/osm-slope#2]
Hello. 

Congrats for your work. 

Is it posible to use the software using highway=motorway as way tag ? Or filter data with max/min speed allowed in each road. 

I am not sure if the calculation is correct using highway=motorway as way tag, there is only few ways calculated using this filter and they are not all motorway. 

Thanks for your time.

**Comment by perliedman** [comment]
Hi there,
looking at the code (https://github.com/perliedman/osm-slope/blob/master/index.js#L17), it definitely looks like this should work for any way that is tagged with the `highway` tag, including `motorway`.

There's currently no other filter funcionality, although that would probably be a pretty straight forward addition.

**Comment by carles3** [comment]
Hello. 

Thanks for your answer. 

It works perfect with 'highway' tag, the tool calculate all ways including motorway, the problem is if i change `if (way.tags('highway')) ` to `if (way.tags('highway=motorway')) ` or `if (way.tags('motorway'))` it does not work or it calculate random ways that are not motorway ways. I am not sure if I am using the correct form to tag only motorway roads.

Thanks for your time.

**Comment by perliedman** [comment]
I think you want:

```js
if (way.tags('highway') === 'motorway')
```

**Comment by carles3** [comment]
Thanks you.

It works perfect now. As you can see I am not expertise on this.

Thanks for your time.



Enviado desde mi smartphone Samsung Galaxy.


-------- Mensaje original --------
De: Per Liedman <notifications@github.com>
Fecha: 29/5/17 12:59 (GMT+01:00)
Para: perliedman/osm-slope <osm-slope@noreply.github.com>
Cc: carles3 <carles_warhammer@hotmail.com>, Author <author@noreply.github.com>
Asunto: Re: [perliedman/osm-slope] highway = motorway as way tag (#2)


I think you want:

if (way.tags('highway') === 'motorway')

**Comment by perliedman** [comment]
Great! Nice to hear you have some use for this module.
